name: QA Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  unit-tests:

    name: Unit Tests + Coverage

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test -- --coverage

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/coverage
